### ISSUE TITLE
CaEnv incompatible with gym>=0.25.x

### ISSUE THREAD

**Issue by Bobobert** [elbecerrasoto/gym-cellular-automata#7]
Throws an assertion error, the observation space is not matching after a reset with gym~=0.26, in version ~=0.25 is not compatible at all.
It seems to run with gym version 0.24.0, last stable fully compatible gym version would be 0.23.1. 
Perhaps moving everything to gymnasium instead.

**Comment by elbecerrasoto** [comment]
I am currently working on the migration to gymnasium.
